speedups:
  parallel_assignment: true
  rescue_vs_respond_to: true
  module_eval: true
  shuffle_first_vs_sample: true
  for_vs_each: true
  each_with_index_vs_while: true
  map_flatten_vs_flat_map: true
  reverse_each_vs_reverese_each: true
  select_first_vs_detect: true
  sort_vs_sort_by: true
  keys_each_vs_each_key: true
  proc_call_vs_yield: true
  gsub_vs_tr: true

